#!/usr/bin/env python3
"""Dump HuggingFace token ids for a fixed corpus -> test/golden/tokenizer.txt.

The bible (§3.3) allows exactly one approximation in the tokenizer: the
pretokenizer regex. This file is how we keep that approximation HONEST — it
measures where our C++ splitter agrees with HF instead of assuming.

Format, one record per line:
    <n_ids> <id> <id> ... \t <python-repr of the string>

test/test_tokenizer.cpp reads it, re-encodes each string with our C++ tokenizer,
and reports per-case pass/fail. Cases known to hit the approximation (digits,
unicode word boundaries) are listed in KNOWN_APPROX so the test can assert
"exact on everything else, and exactly these still differ".
"""
import argparse
import os

CASES = [
    # --- the three oracle prompts: these MUST be exact ---
    "The capital of France is",
    "def fibonacci(n):",
    "Once upon a time, in a land far away,",
    # --- plain ASCII prose ---
    "Hello, world!",
    "hello world",
    " leading space",
    "trailing space ",
    "multiple   spaces   between",
    "\ttab and\nnewline",
    "",
    " ",
    "a",
    # --- punctuation / symbols ---
    "!!!???",
    "a.b.c,d;e:f",
    "(parens) [brackets] {braces}",
    "e-mail: user@example.com",
    "path/to/file.txt",
    # --- contractions (their own regex branch) ---
    "don't can't won't it's I'd we'll they've",
    "DON'T CAN'T",
    # --- code ---
    "for (int i = 0; i < n; ++i) { sum += a[i]; }",
    "#include <immintrin.h>",
    "x = y ** 2 + 3.14",
    # --- digits (GPT-2 vs Qwen digit grouping differs; see KNOWN_APPROX) ---
    "1234567890",
    "The year 2026 and 42 apples",
    "3.14159",
    # --- unicode / emoji / CJK ---
    "café naïve résumé",
    "Ünicode Ümlauts",
    "日本語のテキスト",
    "Привет мир",
    "emoji: 🚀🔥 done",
    "mixed 日本語 and English",
    # --- special tokens must round-trip verbatim ---
    "<|im_start|>user\nhi<|im_end|>",
    "<|endoftext|>",
]

# Cases where our ASCII-exact pretokenizer is EXPECTED to differ from HF.
# The test asserts these are the ONLY differences — if the set shrinks or grows
# unexpectedly, something changed and you want to know.
KNOWN_APPROX_HINT = """\
# Lines whose C++ encoding may differ: those containing digits (Qwen splits
# digits one-per-token via a different \\p{N} rule than GPT-2's run rule) and
# those whose word boundaries need real unicode \\p{L} classification.
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", required=True)
    ap.add_argument("--out", default="test/golden/tokenizer.txt")
    args = ap.parse_args()
    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)

    from transformers import AutoTokenizer
    tok = AutoTokenizer.from_pretrained(args.model)

    with open(args.out, "w", encoding="utf-8") as f:
        f.write("# HuggingFace token-id golden dump. Generated by "
                "tools/dump_tokenizer_golden.py — do not hand-edit.\n")
        f.write(KNOWN_APPROX_HINT)
        for s in CASES:
            ids = tok(s, add_special_tokens=False).input_ids
            f.write(f"{len(ids)} " + " ".join(str(i) for i in ids) + "\t" + repr(s) + "\n")
    print(f"wrote {len(CASES)} cases to {args.out}")


if __name__ == "__main__":
    main()
